---
title: "How to prepare for this workshop"
---

This workshop assumes that participants are already familiar with R and have already installed [R](https://www.r-project.org) (and potentially [RStudio](https://www.rstudio.com/products/rstudio/download/#download)). Please install the below R packages before attending the workshop so that any unforeseen issues can be resolved beforehand.


## Software and tools

Some of the packages used in this workshop require developer tools to be installed before the R package can be successfully downloaded and installed. This will slightly differ depending on the operating system that is used. **This should only be required if downloading directly from GitHub, so it will likely be easier to follow the instructions at the bottom of the page first before trying to install the developer tools described below.**

*For Mac users:*
Per instructions from the `aniMotum` [README](https://github.com/ianjonsen/aniMotum): 

> Ensure you have installed the [Command Line Tools for Xcode](https://developer.apple.com/download/more/) by executing xcode-select --install in the terminal; or you can download the latest version from the URL (free developer registration may be required). A full Xcode install uses up a lot of disk space and is not required. Also, ensure you have a suitable Gnu Fortran compiler installed (e.g., <https://github.com/fxcoudert/gfortran-for-macOS/releases>).


*For PC users:*
Please download [RTools](https://cran.r-project.org/bin/windows/Rtools/), which should install all of the necessary developer tools for you.


## Required R packages

All of the below packages can be installed directly from CRAN using `install.packages()` within the R console. However, more recent versions are likely available from the package's GitHub repo or from an R-Universe repo. This is particularly important for the `aniMotum` package.
<br>

* data wrangling and visualization
  * tidyverse
  * lubridate
  * furrr
  * future
  * plotly
  * tictoc
  * MetBrewer
  * viridis
  * units
  
* spatial analysis
  * sf
  * rnaturalearth
  * rerddapXtracto

* behavioral state estimation
  * aniMotum
  * momentuHMM
  * bayesmove

* space-use estimation
  * amt
  * move


Specifically for the `aniMotum` package, the below instructions are copied from the package's README:

As of `v1.0-5`, `{aniMotum}` is available via R-Universe. This is where the latest stable version can always be found. Installation is simple:
```{r, eval = FALSE}
# install from R-universe repository
install.packages("aniMotum", 
                 repos = c("https://cloud.r-project.org",
                 "https://ianjonsen.r-universe.dev"),
                 dependencies = TRUE)
```
The version on CRAN is no longer being updated, so it is highly recommended that users install a binary or tarball file from the R-Universe or GitHub repositories. Further installation instructions and details for troubleshooting the installation of `aniMotum` can be found on the package [website](https://ianjonsen.github.io/aniMotum/).


