---
title: "Materials"
tbl-colwidths: [10,30,5,5,7]
---

This page contains an outline of the topics, content, and assignments for the workshop. Video recordings will be added after the workshop has ended. Example dataset can be downloaded [here](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/Raw_data/FDN%20Cmydas%20tracks_subset2.csv).

::: column-screen-inset-right
| Date         | Topic                                         |                                                                                   Slides                                                                                    |                                                                                    Code                                                                                     |                                   Video Recording                                    |
|--------------|--------------|:------------:|:-----------------:|:------------:|
| Thurs, Sep 8 | Intro to behavioral state estimation          |             [{{< fa file-pdf size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/Slides/Behavior/Intro_to_movement_ecology.pdf)             |                                                                                                                                                                             |               [{{< fa video size=xl >}}](https://youtu.be/o7-E6-yXytE)               |
|              | Clean and explore tracks                      |                                                                                                                                                                             |        [{{< fa code size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/R_BehavStates/01_Clean%20and%20explore%20tracks.R "R code")         |               [{{< fa video size=xl >}}](https://youtu.be/y7IzVJ5RZP8)               |
|              | Fit SSM via `aniMotum`                        |          [{{< fa file-pdf size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/Slides/Behavior/SSMs%20for%20movement%20ecology.pdf)          |           [{{< fa code size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/R_BehavStates/02_Fit%20SSM%20in%20aniMotum.R "R code")           | [Lecture](https://youtu.be/Zzk6ySuggkA), [Live-coding](https://youtu.be/5CzFESXzlxk) |
|              | Fit HMM via `momentuHMM`                      |          [{{< fa file-pdf size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/Slides/Behavior/HMMs%20for%20movement%20ecology.pdf)          |          [{{< fa code size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/R_BehavStates/03_Fit%20HMM%20in%20momentuHMM.R "R code")          |           [Lecture](https://youtu.be/acTrrhj5ORY), [Live-coding](https://youtu.be/MtUfGHHwatQ)                               |
|              | Fit NP Bayesian models via `bayesmove`        | [{{< fa file-pdf size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/Slides/Behavior/NP%20Bayesian%20models%20for%20movement%20ecology.pdf) | [{{< fa code size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/R_BehavStates/04_Fit%20NP%20Bayesian%20models%20in%20bayesmove.R "R code") |      [Lecture](https://youtu.be/YZDQx9fYWRw), [Live-coding](https://youtu.be/Zi_LkknilK0)                               |
|              | Compare behavioral state estimates            |                                                                                                                                                                             |   [{{< fa code size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/R_BehavStates/05_Compare%20behavioral%20state%20estimates.R "R code")    |                               [{{< fa video size=xl >}}](https://youtu.be/aUWjKsmS6iI)                               |
|              | Recommended guidelines for selecting a method |  [{{< fa file-pdf size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/Slides/Behavior/Guidelines%20for%20estimating%20behav%20states.pdf)   |                                                                                                                                                    |[{{< fa video size=xl >}}](https://youtu.be/MTj_aoTpPy0)                               |
| Fri, Sep 9   | Intro to space-use estimation                 |          [{{< fa file-pdf size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/Slides/Space_Use/Intro%20to%20spatial%20ecology.pdf)          |                                                                                                                                                                             |                               [{{< fa video size=xl >}}](https://youtu.be/8xPMW-xZi9Q)                               |
|              | Estimate space-use with MCP via `amt`         |                                                                                                                                                                             |                       [{{< fa code size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/R_SpaceUse/01_MCPs.R "R code")                       |                               [{{< fa video size=xl >}}](https://youtu.be/rCo4mx8G_qY)                               |
|              | Estimate space-use with KDE via `amt`         |          [{{< fa file-pdf size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/Slides/Space_Use/KDE%20for%20spatial%20ecology.pdf)           |                       [{{< fa code size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/R_SpaceUse/02_KDE.R "R code")                        |                               [Lecture](https://youtu.be/GmuYt3dbTlA), [Live-coding](https://youtu.be/E8fmpOIcPVA)                               |
|              | Estimate space-use with dBBMM via `move`      |         [{{< fa file-pdf size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/Slides/Space_Use/dBBMM%20for%20spatial%20ecology.pdf)          |                      [{{< fa code size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/R_SpaceUse/03_dBBMM.R "R code")                       |                               [Lecture](https://youtu.be/KhJEKr1jcHs), [Live-coding](https://youtu.be/oHCQIGHcwKg)                               |
|              | Compare space-use estimates                   |                                                                                                                                                                             |         [{{< fa code size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/R_SpaceUse/04_Compare%20space-use%20estimates.R "R code")          |                               [{{< fa video size=xl >}}](https://youtu.be/l7YNq54LS8A)                               |
|              | Recommended guidelines for selecting a method |   [{{< fa file-pdf size=xl >}}](https://github.com/joshcullen/Behavior_and_SpaceUse_Workshop/blob/main/Slides/Space_Use/Guidelines%20for%20estimating%20space%20use.pdf)    |                                                                                                                                       |[{{< fa video size=xl >}}](https://youtu.be/_gkLMQ54upc)                               |
:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |       | Slides | Code | Video Recording |
|------|-------|:------:|:----:|:---------------:|
| Date | Topic |   🖥️   |  📋  |       💻        |
