---
title: "Resources related to covered topics"
---

# Other Resources

## R package websites and tutorials
* [`aniMotum` package website](https://ianjonsen.github.io/aniMotum)
* [`momentuHMM` package tutorial](https://cran.r-project.org/web/packages/momentuHMM/vignettes/momentuHMM.pdf)
  - [`momentuHMM` GitHub repo](https://github.com/bmcclintock/momentuHMM)
* [`bayesmove` package website](https://joshcullen.github.io/bayesmove/)
<br><br><br>

* [`amt` package tutorials](https://cran.r-project.org/web/packages/amt/index.html)
  - [`amt` GitHub repo](https://github.com/jmsigner/amt)
* [`move` package website](https://bartk.gitlab.io/move/)


## Additional methods

### Accounting for Argos location error
* `crawl` and `crawlUtils`
  - [publication](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/07-1032.1)
  - [`crawl` GitHub repo](https://github.com/NMML/crawl)
  - [`crawlUtils` GitHub repo](https://github.com/dsjohnson/crawlUtils)
  - [guide to using `crawl`](https://jmlondon.github.io/crawl-workshop/)
* Bayesian state-space models for animal movement (`bsam`)
  - [GitHub repo](https://github.com/ianjonsen/bsam)
  

### Behavioral state estimation
* `seclust2d`
  - [publication](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2656.13105)
  - [package website](https://rpatin.github.io/segclust2d/index.html)
* `hmmTMB`
  - [GitHub repo w/ tutorials](https://github.com/TheoMichelot/hmmTMB)
* move persistence mixed effects model (`mpmm`)
  - [publication](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/ecy.2566)
  - [GitHub repo](https://github.com/ianjonsen/mpmm)
* Bayesian state-space models for animal movement (`bsam`)
  - [GitHub repo](https://github.com/ianjonsen/bsam)


### Space-use estimation
* autocorrelated kernel density estimation (aKDE)
  - [publication](https://repository.si.edu/bitstream/handle/10088/26270/FlemingEtAl2015_Home%20range.pdf?sequence=1&isAllowed=y)
  - [`ctmm` package website](https://ctmm-initiative.github.io/ctmm/index.html)
  - [`ctmmweb` Shiny app](https://ctmm-initiative.github.io/ctmmwebdoc/index.html)
* local convex hull (LoCoH)
  - [publication](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0000207)
  - [`T-LoCoH` package website](https://tlocoh.r-forge.r-project.org)
* movement-based kernel density estimation (MKDE) aka biased random bridges (BRB)
  - [publication](https://wildlife.onlinelibrary.wiley.com/doi/pdfdirect/10.1111/j.1937-2817.2010.tb01257.x?casa_token=9PPoYZbq9IcAAAAA:CsR_G-0UNZudXshUFoNQqBof7q5jVdrIoWmvlivlQ7ho6byjZN5XAXgeA21UUa4G4CgwUpTg-1Plu3zv)
  - [`adehabitatHR` guide](https://cran.r-project.org/web/packages/adehabitatHR/vignettes/adehabitatHR.pdf)
* space-use as function of covariates
  - geostatistical mixed effects models (aka log Gaussian Cox process)
    - [Bakka et al. 2019 "Non-stationary Gaussian models with physical barriers"](https://www.sciencedirect.com/science/article/pii/S221167531830099X?casa_token=v7Cra_Pdf4kAAAAA:5j26CkAhIEYSvl7M1N5pXh01detrbFYDMF6aD1QVVrNf4dlreLnDIuO4kCXJO3Q1z7eum3vYriM)
    - [Winton et al. 2018 "Estimating the distribution and relative density of satellite-tagged loggerhead sea turtles using geostatistical mixed effects models"](https://www.int-res.com/abstracts/meps/v586/p217-232/)
    - [Bachl et al. 2019 "`inlabru`: an R package for Bayesian spatial modelling from ecological survey data"](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13168)
    - [R-INLA package website](https://www.r-inla.org)
    - [inlabru package website](https://sites.google.com/inlabru.org/inlabru)
    - [geospatial INLA examples in R](https://www.paulamoraga.com/book-geospatial/index.html)
  - continuous-time discrete space model
    - [publication](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12967)
    - [CRAN package website](https://cran.r-project.org/web/packages/ctmcmove/index.html)
  - step-selection functions (SSFs)
    - [publication](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.1771)
    - [brief guide from pub](https://esajournals.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fecs2.1771&file=ecs21771-sup-0003-AppendixS3.pdf)
    - [tutorial on fitting SSF w/ `amt`](https://cran.r-project.org/web/packages/amt/vignettes/p4_SSF.html)
  - Brownian bridge covariates model 
    - [publication](https://link.springer.com/article/10.1186/s40462-019-0167-3)
    - [`moveBrownianModel` package website](https://bartk.gitlab.io/moveBrownianModel/)



::: {.column-screen-inset-right}
# Further Readings

## Behavioral state estimation

### State-space models
* Jonsen et al. 2003  [Meta‐analysis of animal movement using state‐space models](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/02-0670)
* Jonsen et al. 2005  [Robust state–space modeling of animal movement data](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/04-1852)
* Jonsen et al. 2007  [Identifying leatherback turtle foraging behaviour from satellite telemetry using a switching state-space model](https://www.int-res.com/articles/meps2007/337/m337p255.pdf)
* Johnson et al. 2008  [Continuous‐time correlated random walk model for animal telemetry data](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/07-1032.1)
* Patterson et al. 2008  [State–space models of individual animal movement](https://www.sciencedirect.com/science/article/pii/S0169534707003588)
* Schick et al. 2008 [Understanding movement data and movement processes: current and emerging directions](https://www.whoi.edu/cms/files/Schick2008_UnderstandingMovementDataProcesses_53549.pdf)
* Breed et al. 2009  [Sex‐specific, seasonal foraging tactics of adult grey seals (*Halichoerus grypus*) revealed by state–space analysis](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/07-1483.1)
* Breed et al. 2012  [State-space methods for more completely capturing behavioral dynamics from animal tracks](https://www.sciencedirect.com/science/article/pii/S0304380012001378)
* Bestley et al. 2013  [Integrative modelling of animal movement: incorporating in situ habitat and behavioural information for a migratory marine predator](https://royalsocietypublishing.org/doi/abs/10.1098/rspb.2012.2262)
* Jonsen et al. 2013  [State-space models for bio-loggers: A methodological road map](https://www.sciencedirect.com/science/article/pii/S096706451200094X)
* McClintock et al. 2013  [Combining individual animal movement and ancillary biotelemetry data to investigate population‐level activity budgets](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/12-0954.1)
* Schick et al. 2013 [Estimating resource acquisition and at‐sea body condition of a marine predator](http://lenthomas.org/papers/SchickJAE2013.pdf)
* Martins et al. 2014  [Behavioral attributes of turbine entrainment risk for adult resident fish revealed by acoustic telemetry and state-space modeling](https://animalbiotelemetry.biomedcentral.com/articles/10.1186/2050-3385-2-13)
* Alos et al. 2016  [Bayesian state-space modelling of conventional acoustic tracking provides accurate descriptors of home range behavior in a small-bodied coastal fish species](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0154089)
* Jonsen et al. 2016  [Joint estimation over multiple individuals improves behavioural state inference from animal movement data](https://www.nature.com/articles/srep20625)
* Auger-Methe et al. 2017  [Spatiotemporal modelling of marine movement data using Template Model Builder (TMB)](https://www.int-res.com/articles/meps2016/565/m565p237.pdf)
* Patterson et al. 2017  [Statistical modelling of individual animal movement: an overview of key methods and a discussion of practical challenges](https://link.springer.com/article/10.1007/s10182-017-0302-7)
* Dorazio and Price 2018  [State-space models to infer movements and behavior of fish detected in a spatial array of acoustic receivers](https://cdnsciencepub.com/doi/abs/10.1139/cjfas-2018-0067?casa_token=RaXph_xXam8AAAAA:6knfzNvKxc5K3nFE1t5ztP1wYvuAEHvCcYu_pK7g5Itgb0kfmkNxyCV81uLHgpxbPYRFC6ckdaTP9w)
* Jonsen et al. 2019  [Movement responses to environment: fast inference of variation among southern elephant seals with a mixed effects model](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/ecy.2566)
* Jonsen et al. 2020  [A continuous-time state-space model for rapid quality control of argos locations from animal-borne tags](https://movementecologyjournal.biomedcentral.com/articles/10.1186/s40462-020-00217-7)
* Auger-Methe et al. 2021  [A guide to state–space modeling of ecological time series](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/ecm.1470)
* Newman et al. 2022 [State‐space models for ecological time‐series data: Practical model‐fitting](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/2041-210X.13833)
* Jonsen et al. 2023 [`aniMotum`, an R package for animal movement data: Rapid quality control, behavioural estimation and simulation](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.14060)


### Hidden Markov models
* Morales et al. 2004  [Extracting more out of relocation data: building movement models as mixtures of random walks](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/03-0269)
* Patterson et al. 2009  [Classifying movement behaviour in relation to environmental conditions using hidden Markov models](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/j.1365-2656.2009.01583.x)
* Langrock et al. 2012  [Flexible and practical modeling of animal telemetry data: hidden Markov models and extensions](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/11-2241.1)
* McClintock et al. 2012  [A general discrete‐time modeling framework for animal movement using multistate random walks](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/11-0326.1)
* Michelot et al. 2016  [`moveHMM`: an R package for the statistical modelling of animal movement data using hidden Markov models](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/2041-210X.12578)
* Leos-Barajas et al. 2017  [Analysis of animal accelerometer data using hidden Markov models](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/2041-210X.12657)
* Leos-Barajas et al. 2017  [Multi-scale modeling of animal movement and general behavior data using hidden Markov models with hierarchical structures](https://link.springer.com/article/10.1007/s13253-017-0282-9)
* Michelot et al. 2017 [Estimation and simulation of foraging trips in land‐based marine predators](https://core.ac.uk/download/pdf/211706757.pdf)
* Patterson et al. 2017  [Statistical modelling of individual animal movement: an overview of key methods and a discussion of practical challenges](https://link.springer.com/article/10.1007/s10182-017-0302-7)
* Pohle et al. 2017  [Selecting the number of states in hidden Markov models: pragmatic solutions illustrated using animal movement](https://link.springer.com/article/10.1007/s13253-017-0283-8)
* Grecian et al. 2018 [Understanding the ontogeny of foraging behaviour: insights from combining marine predator bio-logging with satellite-derived oceanography in hidden Markov models](https://royalsocietypublishing.org/doi/full/10.1098/rsif.2018.0084)
* Langrock et al. 2018  [Spline‐based nonparametric inference in general state‐switching models](https://onlinelibrary.wiley.com/doi/abs/10.1111/stan.12133)
* Leos-Barajas and Michelot 2018  [An introduction to animal movement modeling with hidden Markov Models using Stan for Bayesian inference](https://arxiv.org/pdf/1806.10639.pdf)
* McClintock and Michelot 2018  [`momentuHMM`: R package for generalized hidden Markov models of animal movement](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/2041-210X.12995)
* Adam et al. 2019  [Joint modelling of multi‐scale animal movement data using hierarchical hidden Markov models](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/2041-210X.13241)
* Michelot and Blackwell 2019 [State‐switching continuous‐time correlated random walks](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/2041-210X.13154)
* Carter et al. 2020  [From pup to predator: generalized hidden Markov models reveal rapid development of movement strategies in a naïve long‐lived vertebrate](https://onlinelibrary.wiley.com/doi/abs/10.1111/oik.06853)
* McClintock et al. 2020  [Uncovering ecological state dynamics with hidden Markov models](https://onlinelibrary.wiley.com/doi/abs/10.1111/ele.13610)
* Glennie et al. 2022  [Hidden Markov Models: Pitfalls and Opportunities in Ecology](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/2041-210X.13801)


### Non-parametric Bayesian mixture and mixed-membership models
* Cullen et al. 2022  [Identifying latent behavioural states in animal movement with M4, a nonparametric Bayesian method](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/2041-210X.13745)
* Valle et al. 2022  [Automatic selection of the number of clusters using Bayesian clustering and sparsity-inducing priors](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/eap.2524)
* Cullen et al. 2023  [Biologging as an important tool to uncover behaviors of cryptic species: an analysis of giant armadillos (*Priodontes maximus*)](https://peerj.com/articles/14726/)
* Santos et al. 2023 [Decoding the internesting movements of marine turtles using a finescale behavioral state approach](https://www.frontiersin.org/articles/10.3389/fevo.2023.1229144/)


## Space-use estimation

### Minimum convex polygon
* Worton 1995 [A convex hull-based estimator of home-range size](https://www.jstor.org/stable/pdf/2533254.pdf)
* Nilsen et al. 2008 [Can minimum convex polygon home ranges be used to draw biologically meaningful conclusions?](https://link.springer.com/article/10.1007/s11284-007-0421-9)


### Kernel density estimation
* Worton 1989 [Kernel methods for estimating the utilization distribution in home‐range studies](https://esajournals.onlinelibrary.wiley.com/doi/pdf/10.2307/1938423)
* Seaman and Powell 1996 [An evaluation of the accuracy of kernel density estimators for home range analysis](https://esajournals.onlinelibrary.wiley.com/doi/epdf/10.2307/2265701)
* Gitzen and Millspaugh 2003 [Comparison of least-squares cross-validation bandwidth options for kernel home-range estimation](https://www.jstor.org/stable/pdf/3784605.pdf)
* Fieberg and Kochanny 2005 [Quantifying home‐range overlap: The importance of the utilization distribution](https://wildlife.onlinelibrary.wiley.com/doi/pdfdirect/10.2193/0022-541X%282005%2969%5B1346%3AQHOTIO%5D2.0.CO%3B2)
* Fieberg 2007 [Kernel density estimators of home range: Smoothing and the autocorrelation red herring](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1890/06-0930)
* Boyle et al. 2008 [Home range estimates vary with sample size and methods](https://brill.com/view/journals/ijfp/80/1/article-p33_4.xml)
* Kie et al. 2010 [The home-range concept: are traditional estimators still relevant with modern telemetry technology?](https://royalsocietypublishing.org/doi/full/10.1098/rstb.2010.0093)
* Fieberg and Börger 2012 [Could you please phrase "home range" as a question?](https://academic.oup.com/jmammal/article/93/4/890/962756)
* Fleming et al. 2015 [Rigorous home range estimation with movement data: a new autocorrelated kernel density estimator](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/14-2010.1)
* Fleming and Calabrese 2017 [A new kernel density estimator for accurate home‐range and species‐range area estimation](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/2041-210X.12673)
* Noonan et al. 2019 [A comprehensive analysis of autocorrelation and bias in home range estimation](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecm.1344)
* Signer and Fieberg 2021 [A fresh look at an old concept: home-range estimation in a tidy world](https://peerj.com/articles/11031/?fbclid=IwAR3fH1JNWzk7TIFYS6QY8zQeu2lfUAGx30rZ6Xm-uSsodria6Rtf5pCiUpk&utm_source=TrendMD&utm_campaign=PeerJ_TrendMD_0&utm_medium=TrendMD)
* Fleming et al. 2022 [Population-level inference for home-range areas](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13815)
* Silva et al. 2022 [Autocorrelation-informed home range estimation: A review and practical guide](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.13786)



### Dynamic Brownian bridge movement model
* Horne et al. 2007 [Analyzing animal movements using Brownian bridges](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1890/06-0957.1)
* Kranstauber et al. 2012 [A dynamic Brownian bridge movement model to estimate utilization distributions for heterogeneous animal movement](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/j.1365-2656.2012.01955.x)
* Byrne et al. 2014 [Using dynamic Brownian bridge movement modelling to measure temporal patterns of habitat selection](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2656.12205)
* Silva et al. 2020 [Reptiles on the wrong track? Moving beyond traditional estimators with dynamic Brownian Bridge Movement Models](https://movementecologyjournal.biomedcentral.com/articles/10.1186/s40462-020-00229-3)

:::
